require conf/distro/poky.conf

DISTRO = "kabanos"
DISTRO_NAME = "a minimal podman container distro"
DISTRO_VERSION = "0.1"
MAINTAINER = "Gyokhan Kochmarla <kabanos@gyokhan.com>"

PACKAGE_CLASSES ?= "package_ipk"

DISTRO_FEATURES:append = " ipv6 virtualization "
DISTRO_FEATURES:remove = " wifi bluetooth sound 3g nfc modemmanager pulseaudio"
